version: 1.0.{build}

branches:
  only:
    - master

clone_depth: 2

environment:
  GITHUB_TOKEN:
    secure: 4o8ACklOo/BelSTv6EQZgORUPYFRUP5wgxdgx+Dovb6i2dhgGn25jDep0OuMcDAP

build_script:
- cmd: echo Build %appveyor_build_version%..
- cmd: echo build %appveyor_build_version%>>deploy\build-windows.txt
- cmd: echo.

test_script:
- cmd: echo Test build %appveyor_build_version%..
- cmd: echo.

artifacts:
- path: deploy\build-windows.txt

deploy:
- provider: GitHub
  on:
    branch: master
  auth_token:
    secure: 4o8ACklOo/BelSTv6EQZgORUPYFRUP5wgxdgx+Dovb6i2dhgGn25jDep0OuMcDAP
  tag: master-build
  force_update: true

after_deploy:
- cmd: appveyor-to-gh-pages-branch.cmd
- cmd: appveyor-to-gh-pages-docs.cmd
