version: 1.0.{build}

build_script:
- cmd: echo "Hello"

artifacts:
- path: deploy\index-win.html
  name: TheIndex
  
deploy:
- provider: GitHub
  tag: release-test
  release: release-test
  auth_token:
    secure: n3y7yTAYWRGZctRFYFpyEhV5Bb4SxaH+uba0/T1gLFxZZSujSzru6UhH0xPbHCyq
  artifact: TheIndex
  force_update: true
  on:
    branch: master
