# APPVEYOR_CACHE_SKIP_SAVE: true ?..
# APPVEYOR_CACHE_SKIP_RESTORE

version: 1.0.{build}

branches:
  only:
    - master

test_script:
- cmd: echo "build" %appveyor_build_version%

build_script:
- cmd: echo "build %appveyor_build_version%" >> deploy/index-windows.html

artifacts:
- path: deploy\index-windows.html

deploy:
- provider: GitHub
  on:
    branch: master
  auth_token:
    secure: lvezmyQk31bjzSHu/TMwgx8gRgj8SCsRTI1ZeiLWgUh3LL6I0ecFr7+zLc4fgwsu
  tag: release-test
  force_update: true

after_deploy:
# - sh ./deploy-gh-pages-01.sh  # OK
# - sh ./deploy-gh-pages-02.sh # BAD
# - sh ./deploy-gh-pages-03.sh # ?..

#  - cmd: git config --global credential.helper wincred
#  - cmd: git config --global user.email "djohn7504@gmail.com"
#  - cmd: git config --global user.name "djohn7504"
# - cmd: git --config credentials.helper cache
# - ps: rm -rf out || exit 0;
# - ps: rm -rf out
# - cmd: rmdir out
  - ps: mkdir "out"
  - ps: cd out
  - ps: ls
# - ps: exit 0
  - ps: git clone --branch "gh-pages" https://github.com/djohn7504/lab-ci.git .
  - ps: echo "" >> README.md
  - ps: echo "AppVeyor CI (build $APPVEYOR_BUILD_VERSION)" >> README.md
  - ps: git add README.md
  - ps: git commit --message "Update GitHub Pages."
  - ps: git push --force --quiet "https://$GITHUB_TOKEN@github.com/djohn7504/lab-ci"
