version: 1.0.{build}

branches:
  only:
    - master

clone_depth: 2

environment:
  GITHUB_TOKEN:
    secure: 4o8ACklOo/BelSTv6EQZgORUPYFRUP5wgxdgx+Dovb6i2dhgGn25jDep0OuMcDAP

test_script:
- cmd: echo "Test build" %appveyor_build_version%..
- pwsh: echo "Test build $env:APPVEYOR_BUILD_VERSION.."

build_script:
- cmd: echo "Build %appveyor_build_version%"..
- cmd: echo "build %appveyor_build_version%" >> deploy/index-windows.html
- pwsh: echo "Build $env:APPVEYOR_BUILD_VERSION.."

artifacts:
- path: deploy\index-windows.html

deploy:
- provider: GitHub
  on:
    branch: master
  auth_token:
    secure: 4o8ACklOo/BelSTv6EQZgORUPYFRUP5wgxdgx+Dovb6i2dhgGn25jDep0OuMcDAP
  tag: release-test
  force_update: true

after_deploy:
- cmd: appveyor-to-gh-pages.cmd
