branches:
  only:
    - master

skip_tags: true

install:

test_script:
- echo "Hello" %appveyor_build_version%
- echo %PLATFORM%

build: off

artifacts:
#  - path: deploy
- path: deploy\index-win.html
  name: TheIndex
#  type: File

#deploy: off

deploy:
  provider: GitHub
  description: 'Release description'
#  tag: release-test
  release: release-test
#  release: 1.0.30
  auth_token:
    secure: 7RRqPIF4QkklZNMCs/INNpMUiiYad2N3zxkzgMc6isuBdd95NuoImqA9fzOvrjHg
#  artifact: TheIndex
#  artifact: deploy\index-win.html
  force_update: true
#  draft: true
#  prerelease: false
#  repository: djohn7504/lab-ci
  on:
    branch: master
