version: 1.0.{build}
build_script:
- cmd: echo "Hello"
deploy:
- provider: GitHub
  tag: release-test
  release: release-test
  auth_token:
    secure: n3y7yTAYWRGZctRFYFpyEhV5Bb4SxaH+uba0/T1gLFxZZSujSzru6UhH0xPbHCyq
  artifact: deploy/index-win.html
  force_update: true
  on:
    branch: master
