# APPVEYOR_CACHE_SKIP_SAVE: true ?..
# APPVEYOR_CACHE_SKIP_RESTORE

version: 1.0.{build}

branches:
  only:
    - master

test_script:
- cmd: echo "build" %appveyor_build_version%

build_script:
- cmd: echo "build %appveyor_build_version%" >> deploy/index-windows.html

artifacts:
- path: deploy\index-windows.html

deploy:
- provider: GitHub
  on:
    branch: master
  auth_token:
    secure: 3RFft0fsygMp5QPhBpHu1x61A6dVBv80R6AcZm4QOlv9ITjQjExnJShw1XS251Ju
  tag: release-test
  force_update: true

after_deploy:
#  - sh ./deploy-gh-pages-01.sh  # OK
#  - sh ./deploy-gh-pages-02.sh # BAD
#  - sh ./deploy-gh-pages-03.sh # ?..
