version: 1.0.{build}


#shallow_clone: false


build_script:
- cmd: echo "Hello"

#before_deploy:
#  - ps: echo $artifacts
#  - cmd: dir deploy

#artifacts:
#- path: deploy\index-win.html
#  name: TheIndex
#  type: Zip

deploy:
  provider: GitHub
  description: 'Release description'
#  tag: release-test
#  release: release-test
  auth_token:
    secure: n3y7yTAYWRGZctRFYFpyEhV5Bb4SxaH+uba0/T1gLFxZZSujSzru6UhH0xPbHCyq
#  artifact: TheIndex
#  force_update: true
  draft: true
  prerelease: false
#  repository: djohn7504/lab-ci
  on:
    branch: master
