# APPVEYOR_CACHE_SKIP_SAVE: true ?..
# APPVEYOR_CACHE_SKIP_RESTORE

version: 1.0.{build}

branches:
  only:
    - master

clone_depth: 2

environment:
  GITHUB_TOKEN:
    secure: 4o8ACklOo/BelSTv6EQZgORUPYFRUP5wgxdgx+Dovb6i2dhgGn25jDep0OuMcDAP

test_script:
- cmd: echo "Test build" %appveyor_build_version%..
- pwsh: echo "Test build $env:APPVEYOR_BUILD_VERSION.."

build_script:
- cmd: echo "Build %appveyor_build_version%"..
- cmd: echo "build %appveyor_build_version%" >> deploy/index-windows.html
- pwsh: echo "Build $env:APPVEYOR_BUILD_VERSION.."

artifacts:
- path: deploy\index-windows.html

deploy:
- provider: GitHub
  on:
    branch: master
  auth_token:
    secure: 4o8ACklOo/BelSTv6EQZgORUPYFRUP5wgxdgx+Dovb6i2dhgGn25jDep0OuMcDAP
  tag: release-test
  force_update: true

after_deploy:
- pwsh: echo "After deployement.."
#- pwsh: mkdir "out"
#- pwsh: ls "out"
#- pwsh: ls "./out"
#- pwsh: cd "out"
#- pwsh: ls
#- pwsh: ls "out"
- cmd: dir
#- pwsh: >-
#    mkdir out
#    cd out
#    ls
- cmd: mkdir out
- cmd: cd out
- cmd: dir
- cmd: git config --global user.email "djohn7504@gmail.com"
- cmd: git config --global user.name "djohn7504"
#- pwsh: git clone --branch "gh-pages" https://github.com/djohn7504/lab-ci.git .
- cmd: git clone --branch "gh-pages" https://github.com/djohn7504/lab-ci.git .
- cmd: dir
- cmd: echo.>> README.md
#- cmd: echo "AppVeyor CI (build $env:APPVEYOR_BUILD_VERSION)" >> README.md
- cmd: echo #### AppVeyor CI (build %appveyor_build_version%)>> README.md
- cmd: git add README.md
- cmd: git commit --message "Update GitHub Pages."
#- cmd: git push --force --quiet "https://$env:GITHUB_TOKEN@github.com/djohn7504/lab-ci"
- cmd: git push --force --quiet "https://%GITHUB_TOKEN%@github.com/djohn7504/lab-ci"
#- pwsh: >-
#    echo "" >> README.md
#    echo "AppVeyor CI (build $env:APPVEYOR_BUILD_VERSION)" >> README.md
#    git add README.md
#    git commit --message "Update GitHub Pages."
#    git push --force --quiet "https://$env:GITHUB_TOKEN@github.com/djohn7504/lab-ci"

on_success:
- pwsh: echo "On build success script.."
