branches:
  only:
    - master

skip_tags: true

install:

test_script:
- echo "Hello"

build: off

#artifacts:
#  - path: deploy
#artifacts:
- path: deploy\index-win.html
  name: TheIndex
#  type: Zip

#deploy: off

deploy:
  provider: GitHub
  description: 'Release description'
#  tag: release-test
#  release: release-test
  release: 1.0.30
  auth_token:
    secure: n3y7yTAYWRGZctRFYFpyEhV5Bb4SxaH+uba0/T1gLFxZZSujSzru6UhH0xPbHCyq
  artifact: TheIndex
#  artifact: deploy\index-win.html
#  force_update: true
#  draft: true
#  prerelease: false
#  repository: djohn7504/lab-ci
  on:
    branch: master
