version: 1.0.{build}
branches:
  only:
  - release-test
build:
  verbosity: minimal
deploy:
- provider: GitHub
  auth_token:
    secure: n3y7yTAYWRGZctRFYFpyEhV5Bb4SxaH+uba0/T1gLFxZZSujSzru6UhH0xPbHCyq
  artifact: deploy/index-win.html
  force_update: true
  
