# APPVEYOR_CACHE_SKIP_SAVE: true ?..
# APPVEYOR_CACHE_SKIP_RESTORE

version: 1.0.{build}

branches:
  only:
    - master

test_script:
- cmd: echo "build" %appveyor_build_version%

build_script:
- cmd: echo "build %appveyor_build_version%" >> deploy/index-windows.html

artifacts:
- path: deploy\index-windows.html

deploy:
- provider: GitHub
  on:
    branch: master
  auth_token:
    secure: kO7VTv1Eaoz8h7JS8lZ2KCnd5MoE8hnuUMHvP5KnhrlRAcZiP5MCKlvR/CIbl1qK
  tag: release-test
  force_update: true

after_deploy:
# - sh ./deploy-gh-pages-01.sh  # OK
# - sh ./deploy-gh-pages-02.sh # BAD
# - sh ./deploy-gh-pages-03.sh # ?..

  - cmd: git config --global credential.helper wincred
  - cmd: git config --global user.email "djohn7504@gmail.com"
  - cmd: git config --global user.name "djohn7504"
# - cmd: git --config credentials.helper cache
# - ps: rm -rf out || exit 0;
# - ps: rm -rf out
# - cmd: rmdir out
  - cmd: mkdir "out"
  - ps: ls
# - ps: exit 0
  - cmd: git clone --branch "gh-pages" https://github.com/djohn7504/lab-ci.git "out"
  - ps: cd out
  - ps: echo "Hello Windows (build $APPVEYOR_BUILD_VERSION)" >> index.html
  - cmd: git add .
  - cmd: git commit -m "Deployed to Github Pages"
  - cmd: git push --force --quiet "https://a5e89870d12698c7c82b23ca287bb41e302e16fe@github.com/djohn7504/lab-ci"
