sudo: false
dist: trusty
branches:
  only:
    - master

env:
  global:
    - TAG_TARGET='build.28'
    - TAG_IS_DRAFT=false
    - TAG_IS_PRE_RELEASE=true

script: echo "build.$TRAVIS_BUILD_NUMBER ( from build.28 ) OVERWRITE" >> deploy/index.html

before_deploy:
  - git checkout "$TAG_TARGET"					# <-------- aller dans la bonne branche..

deploy:
  - provider: releases
    on:
      branch: master
    api-key:
      - secure: $GITHUB_TOKEN
    skip-cleanup: true
    overwrite: true								# <-------- écrase les fichiers du tag existant !
    file: deploy/index.html
    verbose: true
    
    tag_name: $TAG_TARGET						# <-------- cible du déploiement
    draft: $TAG_IS_DRAFT
    prerelease: $TAG_IS_PRE_RELEASE
    name: 'Pre-Release (Linux)'
    body: 'Pre-Release: déploiement public des assets, avec les sources (visible par le public)'
