sudo: false

dist: trusty

branches:
  only:
    - master

env:
  global:
    - TAG_TARGET='release-test'
    - TAG_EXIST=`git rev-list --count --max-count=1 release-test`  # 0 or 1

before_script:
  - if [ "$TAG_EXIST" ]; then git checkout "$TAG_TARGET"; else echo "NOT EXIST"; fi

script:
  - echo "build $TRAVIS_BUILD_NUMBER" >> deploy/index-linux.html

befor_deploy:
#  - git config --local user.name "djohn7504"
#  - git config --local user.email "djohn7504@gmail.com"
#  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
#  - git tag $TAG_TARGET

deploy:
  - provider: releases
    on:
      branch: master
#     tags: true
    api-key:
      - secure: $GITHUB_TOKEN
    skip-cleanup: true
    file: deploy/index-linux.html
    tag_name: $TAG_TARGET
    overwrite: true
    verbose: true

after_deploy:
  - "echo 'deployed!'"
  - ls $PWD
  - ./deploy-gh-pages.sh
