sudo: false

dist: trusty

branches:
  only:
    - master

env:
  global:
    - TAG_TARGET='build.28'

script: echo "build.$TRAVIS_BUILD_NUMBER" >> deploy/index.html

before_deploy:
  - git checkout "$TAG_TARGET"					# <-------- aller dans la bonne branche..

deploy:
  - provider: releases
    on:
      branch: master
    api-key:
      - secure: $GITHUB_TOKEN
    skip-cleanup: true
    file: deploy/index.html
    verbose: true
    
    tag_name: $TAG_TARGET						# <-------- cible du déploiement
    overwrite: true								# <-------- écrase les fichiers du tag existant !
