sudo: false
dist: trusty
branches:
  only:
    - master

env:
  - TAG_TARGET='build.28'
  - TAG_IS_DRAFT=false
  - TAG_IS_PRE_RELEASE=true

script: echo "build.$TRAVIS_BUILD_NUMBER ( from build.28 ) OVERWRITE" >> deploy/index.html

before_deploy:
  - git checkout "$TAG_TARGET"					# <-------- try OVERWRITE.....

deploy:
  - provider: releases
    on:
      branch: master
    api-key:
      - secure: $GITHUB_TOKEN
    skip-cleanup: true
    file: deploy/index.html
    verbose: true
#   draft: false
    draft: $TAG_IS_DRAFT
#   prerelease: true
    prerelease: $TAG_IS_PRE_RELEASE
    name: 'Pre-Release (Linux)'
    body: 'Pre-Release: déploiement public des assets, avec les sources (visible par le public)'
    tag_name: $TAG_TARGET						# <-------- cible du déploiement
    overwrite: true								# <-------- écrase les fichiers, si tag exist
