sudo: false

dist: trusty

branches:
  only:
    - master  # <-------- prévient un re-build !

script:
  - echo "build $TRAVIS_BUILD_NUMBER" >> deploy/index.html

#before_deploy:
#  - git tag "build.$TRAVIS_BUILD_NUMBER"  # <-------- doit être unique ?..
#  - git tag "build.20"  # <-------- ..

deploy:
  - provider: releases
    skip-cleanup: true
    file:
      - deploy/index.html
    api-key:
      - secure: $GITHUB_TOKEN
    verbose: true
    overwrite: true  # <-------- ?..
    on:
      branch: master
    draft: true
