sudo: false

dist: trusty

script:
  echo "build $TRAVIS_BUILD_NUMBER" >> deploy/index.html

    before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "djohn7504"
      - git config --local user.email "djohn7504@gmail.com"
      - git tag "1.0"


deploy:
  
#  -provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN
#  keep-history: false
#  local-dir: deploy
#  verbose: true
#  on:
#    branch: master
  
  provider: releases
  skip-cleanup: true
  file: deploy.html
#  api-key:
#    secure: $GITHUB_TOKEN
  user: $GITHUB_USERNAME
  password: $GITHUB_PASSWORD
  verbose: true
  overwrite: true
  on:
    branch: master
