sudo: false

dist: trusty

git:
# depth: 2
  depth: 3000

branches:
  only:
    - master

script:
  - |
    echo "======================================================"
    echo "Travis CI (build $TRAVIS_BUILD_NUMBER)"
    echo "======================================================"

before_deploy:
  # Aller dans la bonne branche, si exist, autrement elle est créée..
# - if [ "$TAG_EXIST" ]; then git checkout "$TAG_TARGET"; else echo "NOT EXIST"; fi
  - git checkout "release-test"

deploy:
  - provider: releases
    on:
      branch: master
    api-key:
      - secure: $GITHUB_TOKEN
    skip-cleanup: true
    file: deploy/index-linux.html
    tag_name: release-test
    overwrite: true
    verbose: true
#   target_commitish: $TRAVIS_COMMIT # <--------both used
#   tag_name: $TRAVIS_TAG # <--------both used

#after_success:
after_deploy:
  - |
    git checkout "master"
    sh travis-to-gh-pages.sh
