sudo: false

dist: trusty

script:
  echo "build $TRAVIS_BUILD_NUMBER" >> deploy/index.html

before_deploy:
  - git tag "v1.0"

deploy:
  - provider: releases
    skip-cleanup: true
    file: deploy/index.html
    api-key:
      secure: $GITHUB_TOKEN
    verbose: true
    overwrite: true
    on:
      branch: master
