sudo: false

dist: trusty

branches:
  only:
    - master									# <-------- prévient un re-build, si releases !

script: echo "build $TRAVIS_BUILD_NUMBER" >> deploy/index.html



deploy:
  - provider: releases
    on:
      branch: master
      tags: false								# <-------- deployment is triggered only if $TRAVIS_TAG is empty.
    api-key:
      - secure: $GITHUB_TOKEN
    skip-cleanup: true
    file:
      - deploy/index.html
    verbose: true
    overwrite: true								# <-------- ?..
    draft: true
    prerelease: true
    name: 'Draft (Linux)'
    body: 'déploie des assets, sans être tagué..'
    
