sudo: false

dist: trusty

branches:
  only:
    - master

script:
  - echo "======================================================"
  - echo "======================================================"
  - echo "======================================================"
#  - git rev-list --count --max-count=1 release-test  # 0 or 1
  - git tag --list