sudo: false

dist: trusty

script:
  echo "build $TRAVIS_BUILD_NUMBER" >> deploy/index.html

#before_deploy:
#  - git tag "1.0"

deploy:
  - provider: releases
    script: git tag "1.0"
    skip-cleanup: true
    file: deploy/index.html
    api-key:
      secure: $GITHUB_TOKEN
    verbose: true
    overwrite: true
    on:
      branch: master

  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    local-dir: deploy
    verbose: true
    on:
      branch: master
