sudo: false

dist: trusty

branches:
  only:
    - master									# <-------- prévient un re-build, si deploy.releases !

env:
  global:
    - TAG_TARGET='release-test'

script: echo "build $TRAVIS_BUILD_NUMBER" >> deploy/index.html

before_deploy:
  - git checkout "$TAG_TARGET"					# <-------- aller dans la bonne branche..

deploy:
  - provider: releases
    on:
      branch: master
    api-key:
      - secure: $GITHUB_TOKEN2
    skip-cleanup: true
    file: deploy/index.html

    tag_name: $TAG_TARGET						# <-------- cible du déploiement
#    tag_name: release-test						# <-------- cible du déploiement			( si on change, alors ancien reste aussi )
    overwrite: true								# <-------- écrase les fichiers du tag existant !
    
#   prerelease: ?								# <-------- on ne peut changer, que le courant !
    prerelease: true
    name: 'Release (Linux)'
    body: 'Release: déploiement public des assets, avec les sources (visible par le public)'

#    name: 'Pre-Release (Linux)'
#    body: 'Pre-Release: déploiement public des assets, avec les sources (visible par le public)'

    verbose: true
#    draft: true										# <-------- NE PAS CHANGER !  (sinon ca change le tag ?..)
