sudo: false

dist: trusty

branches:
  only:
    - master									# <-------- prévient un re-build, si deploy.releases !

env:
  global:
    - TAG_TARGET='new-target'

script: echo "build $TRAVIS_BUILD_NUMBER" >> deploy/index.html

#     OK NEEDED ?!..
#before_deploy:
#  - git checkout "new-target"

deploy:
  - provider: releases
    on:
      branch: master
    api-key:
      - secure: $GITHUB_TOKEN
    skip-cleanup: true
    file: deploy/index.html

    target_commitish: $TRAVIS_COMMIT
    tag_name: new-target
    overwrite: true
    
    verbose: true
