sudo: false

dist: trusty

branches:
  only:
    - master

#script:
before_cache:
  - echo "======================================================"
  - ls
  - echo "======================================================"
  - ls $TRAVIS_BUILD_DIR
  - echo "======================================================"
#  - git rev-list --count --max-count=1 release-test  # 0 or 1
  - git tag --list
  - echo "======================================================"
  - git ls-remote
