sudo: false

dist: trusty

branches:
  only:
    - master

env:
  global:
#   - TAG_TARGET='release-test'
    - TAG_TARGET='master-build'
#   - TAG_EXIST=`git rev-list --count --max-count=1 release-test`  # 0 or 1

script:
  - |
    echo "======================================================"
    echo "Travis CI (build $TRAVIS_BUILD_NUMBER)"
    echo "======================================================"
    echo "build $TRAVIS_BUILD_NUMBER" >> deploy/index-linux.html

before_deploy:

  # see: https://stackoverflow.com/questions/32580821/how-can-i-customize-override-the-git-clone-step-in-travis-ci
  # convert the already existing shallow clone to a full clone
  - git fetch --unshallow --tags

  # *********************************************************************************
  # HACK: pour écraser/compléter les assets d'un tag existant !!!
  # En effet, les assets sont complété par d'autres CI, AppVeyor, etc..
  # *********************************************************************************
  - git checkout $TAG_TARGET
  # TODO: if exist ?..

deploy:
  - provider: releases
    on:
      branch: master
    api-key:
      - secure: $GITHUB_TOKEN
    skip-cleanup: true
    file: deploy/index-linux.html
    tag_name: $TAG_TARGET
    overwrite: true
    verbose: true

after_deploy:
  # *********************************************************************************
  # restore.. (see the HACK)
  # *********************************************************************************
  - git checkout "master"

after_success:
  - sh travis-to-gh-pages.sh
