sudo: false

dist: trusty

git:
  depth: 3000

branches:
  only:
    - master

script:
  - echo "======================================================"
  - echo "script.."
  - echo "======================================================"

#before_cache:
#before_script:
after_script:
  - echo "======================================================"
  - ls
  - echo "======================================================"
#  - ls $TRAVIS_BUILD_DIR
  - echo "======================================================"
#  - git ls-remote --tags 'release-test'
  - git ls-remote --exit-code --tags origin release-test
  - echo "======================================================"
#  - git rev-list --count --max-count=1 release-test  # 0 or 1
#  - git checkout master &&
#  - git checkout master
#  - git checkout release-test
  - git checkout tags/release-test
  - echo "======================================================"
  - git tag --list
  - echo "======================================================"
