sudo: false

dist: trusty

script:
  echo "build $TRAVIS_BUILD_NUMBER" >> deploy/index.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: deploy
  verbose: true
  on:
    branch: master
