sudo: false

dist: trusty

branches:
  only:
    - master

script:
  - echo "======================================================"
  - echo "script.."
  - echo "======================================================"

#before_cache:
#before_script:
after_script:
  - echo "======================================================"
  - ls
  - echo "======================================================"
  - ls $TRAVIS_BUILD_DIR
  - echo "======================================================"
#  - git rev-list --count --max-count=1 release-test  # 0 or 1
  - git checkout master &&
    git tag --list
  - echo "======================================================"
  - git ls-remote
