sudo: false

dist: trusty

branches:
  only:
    - master									# <-------- prévient un re-build, si releases !

#script: echo "build $TRAVIS_BUILD_NUMBER" >> deploy/index.html
script: echo "build.28 OVERWRITE ??????" >> deploy/index.html



before_deploy:
# - git tag "string"							# <-------- inutil si deploy.draft: true
# - git tag "build.$TRAVIS_BUILD_NUMBER"		# <-------- doit être unique ?..
  - git checkout 'build.28'							# <-------- try OVERWRITE.....

#	voir:
#	tag_name: $TRAVIS_TAG		?..


deploy:
  - provider: releases
    on:
      branch: master
#     tags: true								# <-------- deployment is triggered only if $TRAVIS_TAG is set.
#     tags: false								# <-------- deployment is triggered only if $TRAVIS_TAG is empty.
    api-key:
      - secure: $GITHUB_TOKEN
    skip-cleanup: true
    overwrite: true								# <-------- écrase les fichiers du tag ?..
    file: deploy/index.html
    verbose: true
    draft: false
    prerelease: true
    name: 'Pre-Release (Linux)'
    body: 'Pre-Release: déploiement public des assets, avec les sources (visible par le public)'
    tag_name: 'build.28.1'

#   tag_name: $TRAVIS_TAG						# <-------- ?..
