sudo: false

dist: trusty

branches:
  only:
    - master

env:
  global:
    - TAG_TARGET='master-build'

script:
  - |
    echo "======================================================"
    echo "Travis CI (build $TRAVIS_BUILD_NUMBER)"
    echo "======================================================"
    echo "build $TRAVIS_BUILD_NUMBER" >> deploy/index-linux.html

before_deploy:

  # if tag exist..
  # *********************************************************************************
  # HACK: pour écraser/compléter les assets d'un tag existant !!!
  # ( les assets sont complétés par d'autres CI, comme AppVeyor, etc.. )
  - 'if (git ls-remote --exit-code --tags origin $TAG_TARGET >/dev/null) ; then

      git fetch --unshallow --tags;

      git checkout $TAG_TARGET;

    fi'
      # convert the already existing shallow clone to a full clone;
      # HACK: pas top, mais pas trouvé mieux !;
  # *********************************************************************************

deploy:
  - provider: releases
    on:
      branch: master
    api-key:
      - secure: $GITHUB_TOKEN
    skip-cleanup: true
    file: deploy/index-linux.html
    tag_name: $TAG_TARGET
    overwrite: true
    verbose: true

after_deploy:
  # *********************************************************************************
  # restore.. (see the HACK)
  - git checkout "master"
  # *********************************************************************************

  - sh travis-to-gh-pages-branch.sh
  - sh travis-to-gh-pages-docs.sh

#after_success:
