sudo: false

dist: trusty

branches:
  only:
    - master									# <-------- prévient un re-build, si deploy.releases !

env:
  global:
    - TAG_TARGET='release-test'
    - TAG_EXIST=`git rev-list --count --max-count=1 $TAG_TARGET`  # 0 or 1

script: echo "build $TRAVIS_BUILD_NUMBER" >> deploy/index-linux.html

before_deploy:
  # Aller dans la bonne branche, si exist, autrement elle est créée..
  - if [ "$TAG_EXIST" ]; then git checkout "$TAG_TARGET"; else echo "NOT EXIST"; fi
  
deploy:
  - provider: releases
    on:
      branch: master
    api-key:
      - secure: $GITHUB_TOKEN
    skip-cleanup: true
    file: deploy/index-linux.html

    tag_name: $TAG_TARGET						# <-------- cible du déploiement
    overwrite: true								# <-------- écrase les fichiers du tag existant !

    verbose: true
