sudo: false
dist: trusty
branches:
  only:
    - master



env:
  - TAG_SOURCE='build.28'
  - TAG_DESTINATION='build.28.1'
  
# - TAG_DESTINATION=$TRAVIS_BUILD_NUMBER



script: echo "$TRAVIS_BUILD_NUMBER : TAG: $TAG_SOURCE to $TAG_DESTINATION - OVERWRITE ??????" >> deploy/index.html




before_deploy:
  - git checkout "$TAG_SOURCE"					# <-------- try OVERWRITE.....



deploy:
  - provider: releases
    on:
      branch: master
    api-key:
      - secure: $GITHUB_TOKEN
    skip-cleanup: true
    file: deploy/index.html
    verbose: true
    draft: false
    prerelease: true
    name: 'Pre-Release (Linux)'
    body: 'Pre-Release: déploiement public des assets, avec les sources (visible par le public)'
    
    tag_name: $TAG_DESTINATION					# <-------- cible du déploiement
    overwrite: true								# <-------- écrase les fichiers, si tag exist



#	TODO: ..

after_deploy:
  - git push --delete origin "$TAG_SOURCE"		# <-------- try DELETE.....
