sudo: false

dist: trusty

git:
#  depth: 2
 depth: 3000         # !!!


#             *** IMPORTANT ****
#             
#             Travis CI fait un clone, avec une profondeur paramétrable.
#             ex: git clone --depth=2 --branch=master ..
#             Puis, fait un checkout du dernier commit.
#             ex: git checkout -qf 67890fd5bb81dba740fa3ea7b7c3442e89c4bced
#
#             Il ne faut donc pas s'y fier, pour des opération locale, si la profondeur est insufisante !
#             ex: git tag --list    -> peut être vide
#             ex: git checkout tags/release-test


env:
    global:
        # get all the branches referencing this commit
#       - REAL_BRANCH=$(git ls-remote origin | sed -n "\|$TRAVIS_COMMIT\s\+refs/heads/|{s///p}")

        # or check if we are on a particular branch:
#       - IS_RELEASE=$(git ls-remote origin | grep "$TRAVIS_COMMIT\s\+refs/heads/release$")

        - IS_RELEASE_TEST_EXIST=$(git ls-remote --exit-code --tags origin release-test)
#        - IS_RELEASE_TEST_EXIST=$(git ls-remote --exit-code --tags origin DUMMY)
#        - IS_RELEASE_TEST_EXIST=${#git ls-remote --exit-code --tags origin release-test}   # 0, >0   BAD

branches:
  only:
    - master

script:
  - echo "======================================================"
  - echo "script.."
  - echo "======================================================"

#before_cache:
#before_script:
#after_script:
after_success:
  - echo "======================================================"
#  - ls $TRAVIS_BUILD_DIR
  - echo "======================================================"
  - git ls-remote --exit-code --tags origin release-test
  - echo "======================================================"
  - echo "IS_RELEASE_TEST_EXIST:"
  - echo "$IS_RELEASE_TEST_EXIST"
  - echo chrlen=${#IS_RELEASE_TEST_EXIST}         # 0, >0
  - echo "======================================================"
  #- |
  #  if [ $(git ls-remote --exit-code --tags origin release-test) ]; then \
  #    echo "OK exist"; \
  #  else \
  #    echo "NOT exist !!!"; \
  #  fi;
#  - sh travis-to-gh-pages.sh
  - sh travis-to-releases.sh
  - echo "======================================================"
#      exit 1;
